### ISSUE TITLE
[TODO] Todo list

### ISSUE THREAD

**Issue by JBYT27** [JBYT27/YouList#4]
* [ ] #3 
  * [ ] Create navbar
  * [ ] Create better CSS
  * [ ] Create better information
* [ ] #2 
  * [ ] Create the database
  * [ ] Insert the information into the database
* [ ] #1 
  * [ ] Successfully edit the database (playlist)
